all:
	echo prod 

prod:
	cat \
	lib/header.js \
	../jsrsasign-all-min.js \
	lib/footer.js \
	> lib/jsrsasign.js

dev:
	cat \
	lib/header.js \
	../jsrsasign-all.js \
	lib/footer.js \
	> lib/jsrsasign-dev.js
